#pragma once
#include <addon/boss_fakewin.h>
#include <addon/boss_integration_opencv-3.1.0.h>

////////////////////////////////////////////////////////////////////////////////////////////////////
// _BOSS_BATCH_COMMAND_ {"type" : "include-alias", "prm" : "BOSS_OPENCV_", "restore-comment" : " //original-code:"}
#define BOSS_OPENCV_U_eLut_h                                                 "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/eLut.h"
#define BOSS_OPENCV_U_half_h                                                 "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/half.h"
#define BOSS_OPENCV_U_halfFunction_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/halfFunction.h"
#define BOSS_OPENCV_U_halfLimits_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/halfLimits.h"
#define BOSS_OPENCV_U_toFloat_h                                              "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/toFloat.h"
#define BOSS_OPENCV_U_ImathBox_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBox.h"
#define BOSS_OPENCV_U_ImathBoxAlgo_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBoxAlgo.h"
#define BOSS_OPENCV_U_ImathColor_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathColor.h"
#define BOSS_OPENCV_U_ImathColorAlgo_h                                       "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathColorAlgo.h"
#define BOSS_OPENCV_U_ImathEuler_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathEuler.h"
#define BOSS_OPENCV_U_ImathExc_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathExc.h"
#define BOSS_OPENCV_U_ImathFrame_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrame.h"
#define BOSS_OPENCV_U_ImathFrustum_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrustum.h"
#define BOSS_OPENCV_U_ImathFrustumTest_h                                     "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrustumTest.h"
#define BOSS_OPENCV_U_ImathFun_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFun.h"
#define BOSS_OPENCV_U_ImathGL_h                                              "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathGL.h"
#define BOSS_OPENCV_U_ImathGLU_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathGLU.h"
#define BOSS_OPENCV_U_ImathHalfLimits_h                                      "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathHalfLimits.h"
#define BOSS_OPENCV_U_ImathInt64_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathInt64.h"
#define BOSS_OPENCV_U_ImathInterval_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathInterval.h"
#define BOSS_OPENCV_U_ImathLimits_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLimits.h"
#define BOSS_OPENCV_U_ImathLine_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLine.h"
#define BOSS_OPENCV_U_ImathLineAlgo_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLineAlgo.h"
#define BOSS_OPENCV_U_ImathMath_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMath.h"
#define BOSS_OPENCV_U_ImathMatrix_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMatrix.h"
#define BOSS_OPENCV_U_ImathMatrixAlgo_h                                      "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMatrixAlgo.h"
#define BOSS_OPENCV_U_ImathPlane_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathPlane.h"
#define BOSS_OPENCV_U_ImathPlatform_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathPlatform.h"
#define BOSS_OPENCV_U_ImathQuat_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathQuat.h"
#define BOSS_OPENCV_U_ImathRandom_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathRandom.h"
#define BOSS_OPENCV_U_ImathRoots_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathRoots.h"
#define BOSS_OPENCV_U_ImathShear_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathShear.h"
#define BOSS_OPENCV_U_ImathSphere_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathSphere.h"
#define BOSS_OPENCV_U_ImathVec_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathVec.h"
#define BOSS_OPENCV_U_ImathVecAlgo_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathVecAlgo.h"

#define BOSS_OPENCV_V_eLut_h                                                 "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/eLut.h"
#define BOSS_OPENCV_V_half_h                                                 "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/half.h"
#define BOSS_OPENCV_V_halfFunction_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/halfFunction.h"
#define BOSS_OPENCV_V_halfLimits_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/halfLimits.h"
#define BOSS_OPENCV_V_toFloat_h                                              "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Half/toFloat.h"
#define BOSS_OPENCV_V_ImathBox_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBox.h"
#define BOSS_OPENCV_V_ImathBoxAlgo_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBoxAlgo.h"
#define BOSS_OPENCV_V_ImathColor_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathColor.h"
#define BOSS_OPENCV_V_ImathColorAlgo_h                                       "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathColorAlgo.h"
#define BOSS_OPENCV_V_ImathEuler_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathEuler.h"
#define BOSS_OPENCV_V_ImathExc_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathExc.h"
#define BOSS_OPENCV_V_ImathFrame_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrame.h"
#define BOSS_OPENCV_V_ImathFrustum_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrustum.h"
#define BOSS_OPENCV_V_ImathFrustumTest_h                                     "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFrustumTest.h"
#define BOSS_OPENCV_V_ImathFun_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathFun.h"
#define BOSS_OPENCV_V_ImathGL_h                                              "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathGL.h"
#define BOSS_OPENCV_V_ImathGLU_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathGLU.h"
#define BOSS_OPENCV_V_ImathHalfLimits_h                                      "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathHalfLimits.h"
#define BOSS_OPENCV_V_ImathInt64_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathInt64.h"
#define BOSS_OPENCV_V_ImathInterval_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathInterval.h"
#define BOSS_OPENCV_V_ImathLimits_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLimits.h"
#define BOSS_OPENCV_V_ImathLine_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLine.h"
#define BOSS_OPENCV_V_ImathLineAlgo_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathLineAlgo.h"
#define BOSS_OPENCV_V_ImathMath_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMath.h"
#define BOSS_OPENCV_V_ImathMatrix_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMatrix.h"
#define BOSS_OPENCV_V_ImathMatrixAlgo_h                                      "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMatrixAlgo.h"
#define BOSS_OPENCV_V_ImathPlane_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathPlane.h"
#define BOSS_OPENCV_V_ImathPlatform_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathPlatform.h"
#define BOSS_OPENCV_V_ImathQuat_h                                            "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathQuat.h"
#define BOSS_OPENCV_V_ImathRandom_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathRandom.h"
#define BOSS_OPENCV_V_ImathRoots_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathRoots.h"
#define BOSS_OPENCV_V_ImathShear_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathShear.h"
#define BOSS_OPENCV_V_ImathSphere_h                                          "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathSphere.h"
#define BOSS_OPENCV_V_ImathVec_h                                             "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathVec.h"
#define BOSS_OPENCV_V_ImathVecAlgo_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathVecAlgo.h"
