#pragma once
#include <boss.h>
#include <addon/boss_fakewin.h>

////////////////////////////////////////////////////////////////////////////////////////////////////
// _BOSS_BATCH_COMMAND_ {"type" : "include-alias", "prm" : "BOSS_LIBYUV_", "restore-comment" : " //original-code:"}
#define BOSS_LIBYUV_U_libyuv__basic_types_h                          "addon/libyuv-20211215_for_boss/include/libyuv/basic_types.h"
#define BOSS_LIBYUV_U_libyuv__compare_h                              "addon/libyuv-20211215_for_boss/include/libyuv/compare.h"
#define BOSS_LIBYUV_U_libyuv__compare_row_h                          "addon/libyuv-20211215_for_boss/include/libyuv/compare_row.h"
#define BOSS_LIBYUV_U_libyuv__convert_h                              "addon/libyuv-20211215_for_boss/include/libyuv/convert.h"
#define BOSS_LIBYUV_U_libyuv__convert_argb_h                         "addon/libyuv-20211215_for_boss/include/libyuv/convert_argb.h"
#define BOSS_LIBYUV_U_libyuv__convert_from_h                         "addon/libyuv-20211215_for_boss/include/libyuv/convert_from.h"
#define BOSS_LIBYUV_U_libyuv__convert_from_argb_h                    "addon/libyuv-20211215_for_boss/include/libyuv/convert_from_argb.h"
#define BOSS_LIBYUV_U_libyuv__cpu_id_h                               "addon/libyuv-20211215_for_boss/include/libyuv/cpu_id.h"
#define BOSS_LIBYUV_U_libyuv__macros_msa_h                           "addon/libyuv-20211215_for_boss/include/libyuv/macros_msa.h"
#define BOSS_LIBYUV_U_libyuv__mjpeg_decoder_h                        "addon/libyuv-20211215_for_boss/include/libyuv/mjpeg_decoder.h"
#define BOSS_LIBYUV_U_libyuv__planar_functions_h                     "addon/libyuv-20211215_for_boss/include/libyuv/planar_functions.h"
#define BOSS_LIBYUV_U_libyuv__rotate_h                               "addon/libyuv-20211215_for_boss/include/libyuv/rotate.h"
#define BOSS_LIBYUV_U_libyuv__rotate_argb_h                          "addon/libyuv-20211215_for_boss/include/libyuv/rotate_argb.h"
#define BOSS_LIBYUV_U_libyuv__rotate_row_h                           "addon/libyuv-20211215_for_boss/include/libyuv/rotate_row.h"
#define BOSS_LIBYUV_U_libyuv__row_h                                  "addon/libyuv-20211215_for_boss/include/libyuv/row.h"
#define BOSS_LIBYUV_U_libyuv__scale_h                                "addon/libyuv-20211215_for_boss/include/libyuv/scale.h"
#define BOSS_LIBYUV_U_libyuv__scale_argb_h                           "addon/libyuv-20211215_for_boss/include/libyuv/scale_argb.h"
#define BOSS_LIBYUV_U_libyuv__scale_row_h                            "addon/libyuv-20211215_for_boss/include/libyuv/scale_row.h"
#define BOSS_LIBYUV_U_libyuv__scale_uv_h                             "addon/libyuv-20211215_for_boss/include/libyuv/scale_uv.h"
#define BOSS_LIBYUV_U_libyuv__version_h                              "addon/libyuv-20211215_for_boss/include/libyuv/version.h"
#define BOSS_LIBYUV_U_libyuv__video_common_h                         "addon/libyuv-20211215_for_boss/include/libyuv/video_common.h"

// 외부지원
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv_h                    "addon/libyuv-20211215_for_boss/include/libyuv.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__basic_types_h       "addon/libyuv-20211215_for_boss/include/libyuv/basic_types.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__compare_h           "addon/libyuv-20211215_for_boss/include/libyuv/compare.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__compare_row_h       "addon/libyuv-20211215_for_boss/include/libyuv/compare_row.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__convert_h           "addon/libyuv-20211215_for_boss/include/libyuv/convert.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__convert_argb_h      "addon/libyuv-20211215_for_boss/include/libyuv/convert_argb.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__convert_from_h      "addon/libyuv-20211215_for_boss/include/libyuv/convert_from.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__convert_from_argb_h "addon/libyuv-20211215_for_boss/include/libyuv/convert_from_argb.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__cpu_id_h            "addon/libyuv-20211215_for_boss/include/libyuv/cpu_id.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__macros_msa_h        "addon/libyuv-20211215_for_boss/include/libyuv/macros_msa.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__mjpeg_decoder_h     "addon/libyuv-20211215_for_boss/include/libyuv/mjpeg_decoder.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__planar_functions_h  "addon/libyuv-20211215_for_boss/include/libyuv/planar_functions.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__rotate_h            "addon/libyuv-20211215_for_boss/include/libyuv/rotate.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__rotate_argb_h       "addon/libyuv-20211215_for_boss/include/libyuv/rotate_argb.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__rotate_row_h        "addon/libyuv-20211215_for_boss/include/libyuv/rotate_row.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__row_h               "addon/libyuv-20211215_for_boss/include/libyuv/row.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__scale_h             "addon/libyuv-20211215_for_boss/include/libyuv/scale.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__scale_argb_h        "addon/libyuv-20211215_for_boss/include/libyuv/scale_argb.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__scale_row_h         "addon/libyuv-20211215_for_boss/include/libyuv/scale_row.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__scale_uv_h          "addon/libyuv-20211215_for_boss/include/libyuv/scale_uv.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__version_h           "addon/libyuv-20211215_for_boss/include/libyuv/version.h"
#define BOSS_LIBYUV_U_third_party__libyuv__include__libyuv__video_common_h      "addon/libyuv-20211215_for_boss/include/libyuv/video_common.h"
