#pragma once
#include <addon/boss_fakewin.h>

////////////////////////////////////////////////////////////////////////////////////////////////////
// _BOSS_BATCH_COMMAND_ {"type" : "include-alias", "prm" : "BOSS_OPENCV_", "restore-comment" : " //original-code:"}
#define BOSS_OPENCV_V_opencv2__core_hpp                                    <addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core.hpp>
#define BOSS_OPENCV_V_opencv2__core__core_hpp                              <addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/core.hpp>
#define BOSS_OPENCV_V_opencv2__core__core_c_h                              <addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/core_c.h>
#define BOSS_OPENCV_V_opencv2__highgui__highgui_hpp                        <addon/opencv-3.1.0_for_boss/modules/highgui/include/opencv2/highgui/highgui.hpp>
#define BOSS_OPENCV_V_opencv2__imgproc_hpp                                 <addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc.hpp>
#define BOSS_OPENCV_V_opencv2__imgproc__imgproc_hpp                        <addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc/imgproc.hpp>

#define BOSS_OPENCV_U_cvconfig_h                                           "addon/opencv-3.1.0_for_boss/[gen]/cvconfig.h"
#define BOSS_OPENCV_U_opencv2__opencv_modules_hpp                          "addon/opencv-3.1.0_for_boss/[gen]/opencv_modules.hpp"
#define BOSS_OPENCV_U_custom_hal_hpp                                       "addon/opencv-3.1.0_for_boss/[gen]/custom_hal.hpp"
#define BOSS_OPENCV_U_version_string_inc                                   "addon/opencv-3.1.0_for_boss/[gen]/version_string.inc"
#define BOSS_OPENCV_U_opencl_kernels_core_hpp                              "addon/opencv-3.1.0_for_boss/[gen]/opencl_kernels_core.hpp"
#define BOSS_OPENCV_U_opencl_kernels_imgproc_hpp                           "addon/opencv-3.1.0_for_boss/[gen]/opencl_kernels_imgproc.hpp"
#define BOSS_OPENCV_U_opencl_kernels_objdetect_hpp                         "addon/opencv-3.1.0_for_boss/[gen]/opencl_kernels_objdetect.hpp"
#define BOSS_OPENCV_U_opencl_kernels_features2d_hpp                        "addon/opencv-3.1.0_for_boss/[gen]/opencl_kernels_features2d.hpp"
#define BOSS_OPENCV_U_opencl_kernels_video_hpp                             "addon/opencv-3.1.0_for_boss/[gen]/opencl_kernels_video.hpp"

#define BOSS_OPENCV_U_opencv2__opencv_hpp                                  "addon/opencv-3.1.0_for_boss/include/opencv2/opencv.hpp"
#define BOSS_OPENCV_U_opencv2__core_hpp                                    "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core.hpp"
#define BOSS_OPENCV_U_opencv2__core__core_hpp                              "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/core.hpp"
#define BOSS_OPENCV_U_opencv2__core__core_c_h                              "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/core_c.h"
#define BOSS_OPENCV_U_opencv2__core__ocl_hpp                               "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/ocl.hpp"
#define BOSS_OPENCV_U_opencv2__core__cvdef_h                               "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cvdef.h"
#define BOSS_OPENCV_U_opencv2__core__version_hpp                           "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/version.hpp"
#define BOSS_OPENCV_U_opencv2__core__base_hpp                              "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/base.hpp"
#define BOSS_OPENCV_U_opencv2__core__cvstd_hpp                             "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cvstd.hpp"
#define BOSS_OPENCV_U_opencv2__core__traits_hpp                            "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/traits.hpp"
#define BOSS_OPENCV_U_opencv2__core__matx_hpp                              "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/matx.hpp"
#define BOSS_OPENCV_U_opencv2__core__types_hpp                             "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/types.hpp"
#define BOSS_OPENCV_U_opencv2__core__mat_hpp                               "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/mat.hpp"
#define BOSS_OPENCV_U_opencv2__core__persistence_hpp                       "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/persistence.hpp"
#define BOSS_OPENCV_U_opencv2__core__ptr_D_inl_hpp                         "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/ptr.inl.hpp"
#define BOSS_OPENCV_U_opencv2__core__neon_utils_hpp                        "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/neon_utils.hpp"
#define BOSS_OPENCV_U_opencv2__core__sse_utils_hpp                         "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/sse_utils.hpp"
#define BOSS_OPENCV_U_opencv2__core__hal__hal_hpp                          "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/hal/hal.hpp"
#define BOSS_OPENCV_U_opencv2__core__hal__intrin_hpp                       "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/hal/intrin.hpp"
#define BOSS_OPENCV_U_opencv2__core__hal__interface_h                      "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/hal/interface.h"
#define BOSS_OPENCV_U_opencv2__core__hal__intrin_sse_hpp                   "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/hal/intrin_sse.hpp"
#define BOSS_OPENCV_U_opencv2__core__hal__intrin_cpp_hpp                   "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/hal/intrin_cpp.hpp"
#define BOSS_OPENCV_U_opencv2__core__saturate_hpp                          "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/saturate.hpp"
#define BOSS_OPENCV_U_opencv2__core__fast_math_hpp                         "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/fast_math.hpp"
#define BOSS_OPENCV_U_opencv2__core__bufferpool_hpp                        "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/bufferpool.hpp"
#define BOSS_OPENCV_U_opencv2__core__mat_D_inl_hpp                         "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/mat.inl.hpp"
#define BOSS_OPENCV_U_opencv2__core__operations_hpp                        "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/operations.hpp"
#define BOSS_OPENCV_U_opencv2__core__cvstd_D_inl_hpp                       "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cvstd.inl.hpp"
#define BOSS_OPENCV_U_opencv2__core__utility_hpp                           "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/utility.hpp"
#define BOSS_OPENCV_U_opencv2__core__types_c_h                             "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/types_c.h"
#define BOSS_OPENCV_U_opencv2__core__optim_hpp                             "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/optim.hpp"
#define BOSS_OPENCV_U_opencv2__core__affine_hpp                            "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/affine.hpp"
#define BOSS_OPENCV_U_opencv2__core__cuda_hpp                              "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cuda.hpp"
#define BOSS_OPENCV_U_opencv2__core__cuda_types_hpp                        "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cuda_types.hpp"
#define BOSS_OPENCV_U_opencv2__core__cuda_D_inl_hpp                        "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/cuda.inl.hpp"
#define BOSS_OPENCV_U_opencv2__core__directx_hpp                           "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/directx.hpp"
#define BOSS_OPENCV_U_opencv2__core__opengl_hpp                            "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/opengl.hpp"
#define BOSS_OPENCV_U_opencv2__core__va_intel_hpp                          "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/va_intel.hpp"
#define BOSS_OPENCV_U_opencv2__core__private_hpp                           "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/private.hpp"
#define BOSS_OPENCV_U_opencv2__core__private_D_cuda_hpp                    "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/private.cuda.hpp"
#define BOSS_OPENCV_U_opencv2__core__opencl__ocl_defs_hpp                  "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/opencl/ocl_defs.hpp"
#define BOSS_OPENCV_U_opencv2__core__opencl__runtime__opencl_core_hpp      "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/opencl/runtime/opencl_core.hpp"
#define BOSS_OPENCV_U_opencv2__core__opencl__runtime__opencl_clamdblas_hpp "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/opencl/runtime/opencl_clamdblas.hpp"
#define BOSS_OPENCV_U_opencv2__core__opencl__runtime__opencl_clamdfft_hpp  "addon/opencv-3.1.0_for_boss/modules/core/include/opencv2/core/opencl/runtime/opencl_clamdfft.hpp"
#define BOSS_OPENCV_U_opencv2__opencv2__cudabgsegm_hpp                     "addon/opencv-3.1.0_for_boss/modules/cudabgsegm/include/opencv2/cudabgsegm.hpp"
#define BOSS_OPENCV_U_opencv2__highgui_hpp                                 "addon/opencv-3.1.0_for_boss/modules/highgui/include/opencv2/highgui.hpp"
#define BOSS_OPENCV_U_opencv2__highgui__highgui_hpp                        "addon/opencv-3.1.0_for_boss/modules/highgui/include/opencv2/highgui/highgui.hpp"
#define BOSS_OPENCV_U_opencv2__highgui__highgui_c_h                        "addon/opencv-3.1.0_for_boss/modules/highgui/include/opencv2/highgui/highgui_c.h"
#define BOSS_OPENCV_U_opencv2__imgproc_hpp                                 "addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc.hpp"
#define BOSS_OPENCV_U_opencv2__imgproc__imgproc_hpp                        "addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc/imgproc.hpp"
#define BOSS_OPENCV_U_opencv2__imgproc__imgproc_c_h                        "addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc/imgproc_c.h"
#define BOSS_OPENCV_U_opencv2__imgproc__types_c_h                          "addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc/types_c.h"
#define BOSS_OPENCV_U_opencv2__imgproc__detail__distortion_model_hpp       "addon/opencv-3.1.0_for_boss/modules/imgproc/include/opencv2/imgproc/detail/distortion_model.hpp"
#define BOSS_OPENCV_U_opencv2__imgcodecs_hpp                               "addon/opencv-3.1.0_for_boss/modules/imgcodecs/include/opencv2/imgcodecs.hpp"
#define BOSS_OPENCV_U_opencv2__imgcodecs__imgcodecs_c_h                    "addon/opencv-3.1.0_for_boss/modules/imgcodecs/include/opencv2/imgcodecs/imgcodecs_c.h"
#define BOSS_OPENCV_U_opencv2__photo_hpp                                   "addon/opencv-3.1.0_for_boss/modules/photo/include/opencv2/photo.hpp"
#define BOSS_OPENCV_U_opencv2__photo__photo_c_h                            "addon/opencv-3.1.0_for_boss/modules/photo/include/opencv2/photo/photo_c.h"
#define BOSS_OPENCV_U_opencv2__videoio_hpp                                 "addon/opencv-3.1.0_for_boss/modules/videoio/include/opencv2/videoio.hpp"
#define BOSS_OPENCV_U_opencv2__videoio__videoio_c_h                        "addon/opencv-3.1.0_for_boss/modules/videoio/include/opencv2/videoio/videoio_c.h"
#define BOSS_OPENCV_U_opencv2__video_hpp                                   "addon/opencv-3.1.0_for_boss/modules/video/include/opencv2/video.hpp"
#define BOSS_OPENCV_U_opencv2__video__tracking_hpp                         "addon/opencv-3.1.0_for_boss/modules/video/include/opencv2/video/tracking.hpp"
#define BOSS_OPENCV_U_opencv2__video__tracking_c_h                         "addon/opencv-3.1.0_for_boss/modules/video/include/opencv2/video/tracking_c.h"
#define BOSS_OPENCV_U_opencv2__video__background_segm_hpp                  "addon/opencv-3.1.0_for_boss/modules/video/include/opencv2/video/background_segm.hpp"
#define BOSS_OPENCV_U_opencv2__features2d_hpp                              "addon/opencv-3.1.0_for_boss/modules/features2d/include/opencv2/features2d.hpp"
#define BOSS_OPENCV_U_opencv2__flann__miniflann_hpp                        "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/miniflann.hpp"
#define BOSS_OPENCV_U_opencv2__flann__defines_h                            "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/defines.h"
#define BOSS_OPENCV_U_opencv2__flann__dist_h                               "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/dist.h"
#define BOSS_OPENCV_U_opencv2__flann__index_testing_h                      "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/index_testing.h"
#define BOSS_OPENCV_U_opencv2__flann__params_h                             "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/params.h"
#define BOSS_OPENCV_U_opencv2__flann__saving_h                             "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/saving.h"
#define BOSS_OPENCV_U_opencv2__flann__general_h                            "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/general.h"
#define BOSS_OPENCV_U_opencv2__flann__dummy_h                              "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/dummy.h"
#define BOSS_OPENCV_U_opencv2__flann__all_indices_h                        "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/all_indices.h"
#define BOSS_OPENCV_U_opencv2__flann__flann_base_hpp                       "addon/opencv-3.1.0_for_boss/modules/flann/include/opencv2/flann/flann_base.hpp"
#define BOSS_OPENCV_U_opencv2__objdetect_hpp                               "addon/opencv-3.1.0_for_boss/modules/objdetect/include/opencv2/objdetect.hpp"
#define BOSS_OPENCV_U_opencv2__objdetect__objdetect_hpp                    "addon/opencv-3.1.0_for_boss/modules/objdetect/include/opencv2/objdetect/objdetect.hpp"
#define BOSS_OPENCV_U_opencv2__objdetect__objdetect_c_h                    "addon/opencv-3.1.0_for_boss/modules/objdetect/include/opencv2/objdetect/objdetect_c.h"
#define BOSS_OPENCV_U_opencv2__objdetect__detection_based_tracker_hpp      "addon/opencv-3.1.0_for_boss/modules/objdetect/include/opencv2/objdetect/detection_based_tracker.hpp"
#define BOSS_OPENCV_U_opencv2__calib3d_hpp                                 "addon/opencv-3.1.0_for_boss/modules/calib3d/include/opencv2/calib3d.hpp"
#define BOSS_OPENCV_U_opencv2__calib3d__calib3d_c_h                        "addon/opencv-3.1.0_for_boss/modules/calib3d/include/opencv2/calib3d/calib3d_c.h"
#define BOSS_OPENCV_U_opencv2__ml_hpp                                      "addon/opencv-3.1.0_for_boss/modules/ml/include/opencv2/ml.hpp"
#define BOSS_OPENCV_U_opencv2__ml__ml_hpp                                  "addon/opencv-3.1.0_for_boss/modules/ml/include/opencv2/ml/ml.hpp"
#define BOSS_OPENCV_U_opencv2__calib3d__calib3d_hpp                        "addon/opencv-3.1.0_for_boss/modules/calib3d/include/opencv2/calib3d/calib3d.hpp"
#define BOSS_OPENCV_U_opencv2__features2d__features2d_hpp                  "addon/opencv-3.1.0_for_boss/modules/features2d/include/opencv2/features2d/features2d.hpp"
#define BOSS_OPENCV_U_modules__imgproc__src__filterengine_hpp              "addon/opencv-3.1.0_for_boss/modules/imgproc/src/filterengine.hpp"

#define BOSS_OPENCV_V_ImathBox_h                                           <addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBox.h>
#define BOSS_OPENCV_V_ImfChromaticities_h                                  <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfChromaticities.h>
#define BOSS_OPENCV_V_ImfInputFile_h                                       <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfInputFile.h>
#define BOSS_OPENCV_V_ImfChannelList_h                                     <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfChannelList.h>
#define BOSS_OPENCV_V_ImfHeader_h                                          <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfHeader.h>
#define BOSS_OPENCV_V_ImfFrameBuffer_h                                     <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfFrameBuffer.h>
#define BOSS_OPENCV_V_ImfTiledOutputFile_h                                 <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfTiledOutputFile.h>
#define BOSS_OPENCV_V_ImfLineOrder_h                                       <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfLineOrder.h>
#define BOSS_OPENCV_V_ImfCompression_h                                     <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfCompression.h>
#define BOSS_OPENCV_V_ImfName_h                                            <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfName.h>
#define BOSS_OPENCV_V_ImfTileDescription_h                                 <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfTileDescription.h>
#define BOSS_OPENCV_V_ImfThreading_h                                       <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfThreading.h>
#define BOSS_OPENCV_V_ImfInt64_h                                           <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfInt64.h>
#define BOSS_OPENCV_V_ImfPixelType_h                                       <addon/opencv-3.1.0_for_boss/3rdparty/openexr/IlmImf/ImfPixelType.h>
#define BOSS_OPENCV_U_ImathBox_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathBox.h"
#define BOSS_OPENCV_U_ImathVec_h                                           "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathVec.h"
#define BOSS_OPENCV_U_ImathMatrix_h                                        "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathMatrix.h"
#define BOSS_OPENCV_U_ImathInt64_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Imath/ImathInt64.h"
#define BOSS_OPENCV_U_IexBaseExc_h                                         "addon/opencv-3.1.0_for_boss/3rdparty/openexr/Iex/IexBaseExc.h"
