#pragma once
#include <boss.h>
#include <addon/boss_fakewin.h>

#undef max
#undef min
#define ABSL_STACKTRACE_INL_HEADER \
    "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/stacktrace_win32-inl.inc"

////////////////////////////////////////////////////////////////////////////////////////////////////
// _BOSS_BATCH_COMMAND_ {"type" : "include-alias", "prm" : "BOSS_ABSEILCPP_", "restore-comment" : " //original-code:"}
#define BOSS_ABSEILCPP_U_absl__algorithm__algorithm_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/algorithm/algorithm.h"
#define BOSS_ABSEILCPP_U_absl__algorithm__container_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/algorithm/container.h"

#define BOSS_ABSEILCPP_U_absl__base__attributes_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/base/attributes.h"
#define BOSS_ABSEILCPP_U_absl__base__call_once_h                                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/call_once.h"
#define BOSS_ABSEILCPP_U_absl__base__casts_h                                            "addon/abseil-cpp-20211102.0_for_boss/absl/base/casts.h"
#define BOSS_ABSEILCPP_U_absl__base__config_h                                           "addon/abseil-cpp-20211102.0_for_boss/absl/base/config.h"
#define BOSS_ABSEILCPP_U_absl__base__const_init_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/base/const_init.h"
#define BOSS_ABSEILCPP_U_absl__base__dynamic_annotations_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/base/dynamic_annotations.h"
#define BOSS_ABSEILCPP_U_absl__base__log_severity_h                                     "addon/abseil-cpp-20211102.0_for_boss/absl/base/log_severity.h"
#define BOSS_ABSEILCPP_U_absl__base__macros_h                                           "addon/abseil-cpp-20211102.0_for_boss/absl/base/macros.h"
#define BOSS_ABSEILCPP_U_absl__base__optimization_h                                     "addon/abseil-cpp-20211102.0_for_boss/absl/base/optimization.h"
#define BOSS_ABSEILCPP_U_absl__base__options_h                                          "addon/abseil-cpp-20211102.0_for_boss/absl/base/options.h"
#define BOSS_ABSEILCPP_U_absl__base__policy_checks_h                                    "addon/abseil-cpp-20211102.0_for_boss/absl/base/policy_checks.h"
#define BOSS_ABSEILCPP_U_absl__base__port_h                                             "addon/abseil-cpp-20211102.0_for_boss/absl/base/port.h"
#define BOSS_ABSEILCPP_U_absl__base__thread_annotations_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/base/thread_annotations.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__atomic_hook_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/atomic_hook.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__atomic_hook_test_helper_h                "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/atomic_hook_test_helper.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__cycleclock_h                             "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/cycleclock.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__direct_mmap_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/direct_mmap.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__dynamic_annotations_h                    "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/dynamic_annotations.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__endian_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/endian.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__errno_saver_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/errno_saver.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__exception_safety_testing_h               "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/exception_safety_testing.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__exception_testing_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/exception_testing.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__fast_type_id_h                           "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/fast_type_id.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__hide_ptr_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/hide_ptr.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__identity_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/identity.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__inline_variable_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/inline_variable.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__inline_variable_testing_h                "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/inline_variable_testing.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__invoke_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/invoke.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__low_level_alloc_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/low_level_alloc.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__low_level_scheduling_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/low_level_scheduling.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__per_thread_tls_h                         "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/per_thread_tls.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__pretty_function_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/pretty_function.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__raw_logging_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/raw_logging.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__scheduling_mode_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/scheduling_mode.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__scoped_set_env_h                         "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/scoped_set_env.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__spinlock_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/spinlock.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__spinlock_wait_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/spinlock_wait.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__strerror_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/strerror.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__sysinfo_h                                "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/sysinfo.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__thread_annotations_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/thread_annotations.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__thread_identity_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/thread_identity.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__throw_delegate_h                         "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/throw_delegate.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__tsan_mutex_interface_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/tsan_mutex_interface.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__unaligned_access_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/unaligned_access.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__unscaledcycleclock_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/unscaledcycleclock.h"
#define BOSS_ABSEILCPP_U_absl__base__internal__spinlock_win32_inc                       "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/spinlock_win32.inc"
#define BOSS_ABSEILCPP_U_absl__base__internal__spinlock_akaros_inc                      "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/spinlock_akaros.inc"
#define BOSS_ABSEILCPP_U_absl__base__internal__spinlock_posix_inc                       "addon/abseil-cpp-20211102.0_for_boss/absl/base/internal/spinlock_posix.inc"

#define BOSS_ABSEILCPP_U_absl__container__btree_map_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/container/btree_map.h"
#define BOSS_ABSEILCPP_U_absl__container__btree_set_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/container/btree_set.h"
#define BOSS_ABSEILCPP_U_absl__container__btree_test_h                                  "addon/abseil-cpp-20211102.0_for_boss/absl/container/btree_test.h"
#define BOSS_ABSEILCPP_U_absl__container__fixed_array_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/container/fixed_array.h"
#define BOSS_ABSEILCPP_U_absl__container__flat_hash_map_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/container/flat_hash_map.h"
#define BOSS_ABSEILCPP_U_absl__container__flat_hash_set_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/container/flat_hash_set.h"
#define BOSS_ABSEILCPP_U_absl__container__inlined_vector_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/container/inlined_vector.h"
#define BOSS_ABSEILCPP_U_absl__container__node_hash_map_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/container/node_hash_map.h"
#define BOSS_ABSEILCPP_U_absl__container__node_hash_set_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/container/node_hash_set.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__btree_h                             "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/btree.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__btree_container_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/btree_container.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__common_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/common.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__compressed_tuple_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/compressed_tuple.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__container_memory_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/container_memory.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__counting_allocator_h                "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/counting_allocator.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hash_function_defaults_h            "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hash_function_defaults.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hash_generator_testing_h            "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hash_generator_testing.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hash_policy_testing_h               "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hash_policy_testing.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hash_policy_traits_h                "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hash_policy_traits.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hashtable_debug_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hashtable_debug.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hashtable_debug_hooks_h             "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hashtable_debug_hooks.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__hashtablez_sampler_h                "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/hashtablez_sampler.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__have_sse_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/have_sse.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__inlined_vector_h                    "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/inlined_vector.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__layout_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/layout.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__node_hash_policy_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/node_hash_policy.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__raw_hash_map_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/raw_hash_map.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__raw_hash_set_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/raw_hash_set.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__test_instance_tracker_h             "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/test_instance_tracker.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__tracked_h                           "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/tracked.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_map_constructor_test_h    "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_map_constructor_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_map_lookup_test_h         "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_map_lookup_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_map_members_test_h        "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_map_members_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_map_modifiers_test_h      "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_map_modifiers_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_set_constructor_test_h    "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_set_constructor_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_set_lookup_test_h         "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_set_lookup_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_set_members_test_h        "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_set_members_test.h"
#define BOSS_ABSEILCPP_U_absl__container__internal__unordered_set_modifiers_test_h      "addon/abseil-cpp-20211102.0_for_boss/absl/container/internal/unordered_set_modifiers_test.h"

#define BOSS_ABSEILCPP_U_absl__debugging__failure_signal_handler_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/failure_signal_handler.h"
#define BOSS_ABSEILCPP_U_absl__debugging__leak_check_h                                  "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/leak_check.h"
#define BOSS_ABSEILCPP_U_absl__debugging__stacktrace_h                                  "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/stacktrace.h"
#define BOSS_ABSEILCPP_U_absl__debugging__symbolize_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/symbolize.h"
#define BOSS_ABSEILCPP_U_absl__debugging__symbolize_elf_inc                             "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/symbolize_elf.inc"
#define BOSS_ABSEILCPP_U_absl__debugging__symbolize_unimplemented_inc                   "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/symbolize_unimplemented.inc"
#define BOSS_ABSEILCPP_U_absl__debugging__symbolize_win32_inc                           "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/symbolize_win32.inc"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__address_is_readable_h               "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/address_is_readable.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__demangle_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/demangle.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__elf_mem_image_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/elf_mem_image.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__examine_stack_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/examine_stack.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__stack_consumption_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/stack_consumption.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__stacktrace_config_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/stacktrace_config.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__symbolize_h                         "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/symbolize.h"
#define BOSS_ABSEILCPP_U_absl__debugging__internal__vdso_support_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/debugging/internal/vdso_support.h"

#define BOSS_ABSEILCPP_U_absl__flags__commandlineflag_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/flags/commandlineflag.h"
#define BOSS_ABSEILCPP_U_absl__flags__config_h                                          "addon/abseil-cpp-20211102.0_for_boss/absl/flags/config.h"
#define BOSS_ABSEILCPP_U_absl__flags__declare_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/flags/declare.h"
#define BOSS_ABSEILCPP_U_absl__flags__flag_h                                            "addon/abseil-cpp-20211102.0_for_boss/absl/flags/flag.h"
#define BOSS_ABSEILCPP_U_absl__flags__marshalling_h                                     "addon/abseil-cpp-20211102.0_for_boss/absl/flags/marshalling.h"
#define BOSS_ABSEILCPP_U_absl__flags__parse_h                                           "addon/abseil-cpp-20211102.0_for_boss/absl/flags/parse.h"
#define BOSS_ABSEILCPP_U_absl__flags__reflection_h                                      "addon/abseil-cpp-20211102.0_for_boss/absl/flags/reflection.h"
#define BOSS_ABSEILCPP_U_absl__flags__usage_h                                           "addon/abseil-cpp-20211102.0_for_boss/absl/flags/usage.h"
#define BOSS_ABSEILCPP_U_absl__flags__usage_config_h                                    "addon/abseil-cpp-20211102.0_for_boss/absl/flags/usage_config.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__commandlineflag_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/commandlineflag.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__flag_h                                  "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/flag.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__parse_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/parse.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__path_util_h                             "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/path_util.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__private_handle_accessor_h               "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/private_handle_accessor.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__program_name_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/program_name.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__registry_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/registry.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__sequence_lock_h                         "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/sequence_lock.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__usage_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/usage.h"
#define BOSS_ABSEILCPP_U_absl__flags__internal__flag_msvc_inc                           "addon/abseil-cpp-20211102.0_for_boss/absl/flags/internal/flag_msvc.inc"

#define BOSS_ABSEILCPP_U_absl__functional__bind_front_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/functional/bind_front.h"
#define BOSS_ABSEILCPP_U_absl__functional__internal__front_binder_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/functional/internal/front_binder.h"

#define BOSS_ABSEILCPP_U_absl__memory__memory_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/memory/memory.h"

#define BOSS_ABSEILCPP_U_absl__meta__type_traits_h                                      "addon/abseil-cpp-20211102.0_for_boss/absl/meta/type_traits.h"

#define BOSS_ABSEILCPP_U_absl__numeric__bits_h                                          "addon/abseil-cpp-20211102.0_for_boss/absl/numeric/bits.h"
#define BOSS_ABSEILCPP_U_absl__numeric__int128_h                                        "addon/abseil-cpp-20211102.0_for_boss/absl/numeric/int128.h"
#define BOSS_ABSEILCPP_U_absl__numeric__int128_have_intrinsic_inc                       "addon/abseil-cpp-20211102.0_for_boss/absl/numeric/int128_have_intrinsic.inc"
#define BOSS_ABSEILCPP_U_absl__numeric__int128_no_intrinsic_inc                         "addon/abseil-cpp-20211102.0_for_boss/absl/numeric/int128_no_intrinsic.inc"
#define BOSS_ABSEILCPP_U_absl__numeric__internal__bits_h                                "addon/abseil-cpp-20211102.0_for_boss/absl/numeric/internal/bits.h"

#define BOSS_ABSEILCPP_U_absl__strings__ascii_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/strings/ascii.h"
#define BOSS_ABSEILCPP_U_absl__strings__charconv_h                                      "addon/abseil-cpp-20211102.0_for_boss/absl/strings/charconv.h"
#define BOSS_ABSEILCPP_U_absl__strings__escaping_h                                      "addon/abseil-cpp-20211102.0_for_boss/absl/strings/escaping.h"
#define BOSS_ABSEILCPP_U_absl__strings__match_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/strings/match.h"
#define BOSS_ABSEILCPP_U_absl__strings__numbers_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/numbers.h"
#define BOSS_ABSEILCPP_U_absl__strings__str_cat_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/str_cat.h"
#define BOSS_ABSEILCPP_U_absl__strings__str_join_h                                      "addon/abseil-cpp-20211102.0_for_boss/absl/strings/str_join.h"
#define BOSS_ABSEILCPP_U_absl__strings__str_replace_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/strings/str_replace.h"
#define BOSS_ABSEILCPP_U_absl__strings__str_split_h                                     "addon/abseil-cpp-20211102.0_for_boss/absl/strings/str_split.h"
#define BOSS_ABSEILCPP_U_absl__strings__string_view_h                                   "addon/abseil-cpp-20211102.0_for_boss/absl/strings/string_view.h"
#define BOSS_ABSEILCPP_U_absl__strings__strip_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/strings/strip.h"
#define BOSS_ABSEILCPP_U_absl__strings__substitute_h                                    "addon/abseil-cpp-20211102.0_for_boss/absl/strings/substitute.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__char_map_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/char_map.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__charconv_bigint_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/charconv_bigint.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__charconv_parse_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/charconv_parse.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_internal_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_internal.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_btree_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_btree.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_btree_navigator_h            "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_btree_navigator.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_btree_reader_h               "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_btree_reader.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_consume_h                    "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_consume.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_flat_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_flat.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_ring_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_ring.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_ring_reader_h                "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_ring_reader.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cord_rep_test_util_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cord_rep_test_util.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_functions_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_functions.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_handle_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_handle.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_info_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_info.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_sample_token_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_sample_token.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_statistics_h                    "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_statistics.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_update_scope_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_update_scope.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__cordz_update_tracker_h                "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/cordz_update_tracker.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__escaping_h                            "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/escaping.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__escaping_test_common_h                "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/escaping_test_common.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__memutil_h                             "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/memutil.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__numbers_test_common_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/numbers_test_common.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__ostringstream_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/ostringstream.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__pow10_helper_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/pow10_helper.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__resize_uninitialized_h                "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/resize_uninitialized.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__stl_type_traits_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/stl_type_traits.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__str_join_internal_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/str_join_internal.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__str_split_internal_h                  "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/str_split_internal.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__string_constant_h                     "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/string_constant.h"
#define BOSS_ABSEILCPP_U_absl__strings__internal__utf8_h                                "addon/abseil-cpp-20211102.0_for_boss/absl/strings/internal/utf8.h"

#define BOSS_ABSEILCPP_U_absl__synchronization__barrier_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/barrier.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__blocking_counter_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/blocking_counter.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__mutex_h                                 "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/mutex.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__notification_h                          "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/notification.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__create_thread_identity_h      "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/create_thread_identity.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__futex_h                       "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/futex.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__graphcycles_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/graphcycles.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__kernel_timeout_h              "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/kernel_timeout.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__per_thread_sem_h              "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/per_thread_sem.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__thread_pool_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/thread_pool.h"
#define BOSS_ABSEILCPP_U_absl__synchronization__internal__waiter_h                      "addon/abseil-cpp-20211102.0_for_boss/absl/synchronization/internal/waiter.h"

#define BOSS_ABSEILCPP_U_absl__time__civil_time_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/time/civil_time.h"
#define BOSS_ABSEILCPP_U_absl__time__clock_h                                            "addon/abseil-cpp-20211102.0_for_boss/absl/time/clock.h"
#define BOSS_ABSEILCPP_U_absl__time__time_h                                             "addon/abseil-cpp-20211102.0_for_boss/absl/time/time.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__test_util_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/test_util.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__cctz__include__cctz__civil_time_h        "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/cctz/include/cctz/civil_time.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__cctz__include__cctz__civil_time_detail_h "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/cctz/include/cctz/civil_time_detail.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__cctz__include__cctz__time_zone_h         "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/cctz/include/cctz/time_zone.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__cctz__include__cctz__zone_info_source_h  "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/cctz/include/cctz/zone_info_source.h"
#define BOSS_ABSEILCPP_U_absl__time__internal__get_current_time_chrono_inc              "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/get_current_time_chrono.inc"
#define BOSS_ABSEILCPP_U_absl__time__internal__get_current_time_posix_inc               "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/get_current_time_posix.inc"
#define BOSS_ABSEILCPP_U_absl__time__internal__zoneinfo_inc                             "addon/abseil-cpp-20211102.0_for_boss/absl/time/internal/zoneinfo.inc"

#define BOSS_ABSEILCPP_U_absl__types__any_h                                             "addon/abseil-cpp-20211102.0_for_boss/absl/types/any.h"
#define BOSS_ABSEILCPP_U_absl__types__bad_any_cast_h                                    "addon/abseil-cpp-20211102.0_for_boss/absl/types/bad_any_cast.h"
#define BOSS_ABSEILCPP_U_absl__types__bad_optional_access_h                             "addon/abseil-cpp-20211102.0_for_boss/absl/types/bad_optional_access.h"
#define BOSS_ABSEILCPP_U_absl__types__bad_variant_access_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/types/bad_variant_access.h"
#define BOSS_ABSEILCPP_U_absl__types__optional_h                                        "addon/abseil-cpp-20211102.0_for_boss/absl/types/optional.h"
#define BOSS_ABSEILCPP_U_absl__types__span_h                                            "addon/abseil-cpp-20211102.0_for_boss/absl/types/span.h"
#define BOSS_ABSEILCPP_U_absl__types__variant_h                                         "addon/abseil-cpp-20211102.0_for_boss/absl/types/variant.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__conformance_aliases_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/conformance_aliases.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__conformance_archetype_h                 "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/conformance_archetype.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__conformance_profile_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/conformance_profile.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__conformance_testing_h                   "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/conformance_testing.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__conformance_testing_helpers_h           "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/conformance_testing_helpers.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__optional_h                              "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/optional.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__parentheses_h                           "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/parentheses.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__span_h                                  "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/span.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__transform_args_h                        "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/transform_args.h"
#define BOSS_ABSEILCPP_U_absl__types__internal__variant_h                               "addon/abseil-cpp-20211102.0_for_boss/absl/types/internal/variant.h"

#define BOSS_ABSEILCPP_U_absl__utility__utility_h                                       "addon/abseil-cpp-20211102.0_for_boss/absl/utility/utility.h"
